name: network

services:

  network-mkdocs:
    image: ghcr.io/tiogars/mkdocs-docker-image:latest
    hostname: network-mkdocs
    container_name: network-mkdocs
    working_dir: /server/
    volumes:
      - ./docs:/server/docs
      - ./mkdocs.yml:/server/mkdocs.yml
    command: ["serve","--dev-addr=0.0.0.0:8000"]
    environment:
      - TZ=Europe/Paris
    ports:
      - "8000:8000"