site_name: Network Documentation
site_url: https://docs.network.tiogars.fr/
repo_url: https://github.com/tiogars/network
site_description: Documentation for network
site_author: Tiogars
nav:
  - Home: index.md
  - Models:
    - Introduction: models/index.md
    - Network: models/network.md
    - Device: models/device.md
    - Interface: models/interface.md
theme:
  # name: readthedocs
  name: material
  locale: en
  highlightjs: true
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search:
  - kroki:
      FencePrefix: ''
      FileTypeOverrides:
        mermaid: png
  - macros:
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs 
  - with-pdf:
      author: Tiogars
      copyright: ©2025
      cover_subtitle: Documentation
      output_path: fr.tiogars.network.docs.pdf
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
    - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js